#!/usr/bin/env python3
"""Derive the wave view from the plan's item table.

The wave table drifted from the item table five times in five
amendments — BV7, BV9 and three before them — and the fifth drift was
the repair for the fourth. A hand-maintained second copy of one graph is
the defect; this replaces it.

Reads the `Blocks-start` column of the item table in
`plan-01-part2-part0.md`, computes topological levels, and prints the
wave view. Blocks-trust edges are deliberately NOT levels: per PA6 they
constrain whether an item's output is evidence, not when it can start.

    python3 docs/plan/derive-waves.py            # print the derived view
    python3 docs/plan/derive-waves.py --check    # exit 1 if the document
                                                 # disagrees with it

Ownership note: this generates content for a document H owns. If it
should instead be project tooling under `scripts/` with a Makefile
target, that is the human's call — `scripts/` is human-owned.
"""
import re
import sys
from pathlib import Path

DOC = Path(__file__).with_name("plan-01-part2-part0.md")
ITEM_RE = re.compile(r"^\|\s*\*\*(P\d+[ab]?)\*\*\s*\|")
# An edge is a bare item id. Prose in the column ("source access this
# repo lacks") is not an edge and must not be silently read as one.
EDGE_RE = re.compile(r"^P\d+[ab]?$")


def parse_items(text):
    """Return {item: [blocks-start deps]} plus any non-edge cell text."""
    items, unparsed = {}, {}
    for line in text.splitlines():
        m = ITEM_RE.match(line)
        if not m:
            continue
        cells = [c.strip() for c in line.split("|")[1:-1]]
        if len(cells) < 5:
            continue
        item = m.group(1)
        raw = cells[3]
        deps, notes = [], []
        for part in raw.split(","):
            tok = part.strip().strip("*` ")
            if not tok or tok == "—":
                continue
            if EDGE_RE.match(tok):
                deps.append(tok)
            else:
                notes.append(tok)
        items[item] = deps
        if notes:
            unparsed[item] = notes
    return items, unparsed


def parse_done(text):
    """Return {item: size} from the definition-of-done table."""
    done = {}
    for line in text.splitlines():
        m = ITEM_RE.match(line)
        if not m:
            continue
        cells = [c.strip() for c in line.split("|")[1:-1]]
        # BV17 surfaced a second shape: PA16's table is
        # (id, criterion, size); PA22's is (id, item, criterion, size).
        # The item table is 6. Size is always the last cell.
        if len(cells) not in (3, 4):
            continue
        size = cells[-1].strip("*~` ")
        done[m.group(1)] = size
    return done


def levels(items, unstartable):
    """Topological levels.

    BV18: a dependency on an item that is not startable here makes the
    dependent not startable either. The earlier version skipped such
    deps, which put dependents of P12 in wave 1 — failing toward
    *startable*, the wrong direction.
    """
    level, remaining = {}, dict(items)
    blocked_by_unstartable = {}
    n = 0
    while remaining:
        for i, d in list(remaining.items()):
            if any(x in unstartable or x in blocked_by_unstartable for x in d):
                blocked_by_unstartable[i] = [
                    x for x in d if x in unstartable or x in blocked_by_unstartable]
                del remaining[i]
        ready = [i for i, d in remaining.items() if all(x in level for x in d)]
        if not ready:
            break
        for i in ready:
            level[i] = n
            del remaining[i]
        n += 1
    return level, remaining, blocked_by_unstartable


def _key(i):
    m = re.match(r"P(\d+)([ab]?)", i)
    return (int(m.group(1)), m.group(2))


def render(items, level, blocked, unparsed, downstream):
    out = []
    out.append("<!-- GENERATED by docs/plan/derive-waves.py — do not hand-edit. -->")
    out.append("")
    out.append("| Wave | Items |")
    out.append("|---|---|")
    for n in range(max(level.values(), default=-1) + 1):
        members = sorted((i for i, l in level.items() if l == n), key=_key)
        out.append(f"| **{n + 1}** | {', '.join('**%s**' % m for m in members)} |")
    for item, notes in sorted(unparsed.items(), key=lambda kv: _key(kv[0])):
        out.append(f"| **—** | **{item}** — not startable here: {'; '.join(notes)} |")
    for item, deps in sorted(downstream.items(), key=lambda kv: _key(kv[0])):
        out.append(f"| **—** | **{item}** — downstream of {', '.join(sorted(deps, key=_key))}, "
                   f"which is not startable here |")
    if blocked:
        out.append(f"| **cycle** | {', '.join(sorted(blocked))} |")
    return "\n".join(out)


def main():
    text = DOC.read_text()
    items, unparsed = parse_items(text)
    done = parse_done(text)
    all_ids = set(items)
    # An item whose only "dependency" is prose has no computable level.
    for item in unparsed:
        items.pop(item, None)

    errors = []
    # BV18: a Blocks-start naming an id that does not exist is a typo,
    # not an absent dependency. Silently accepting it fails toward
    # *startable*.
    for i, deps in items.items():
        for d in deps:
            if d not in all_ids:
                errors.append(f"{i} depends on {d}, which is not an item")
    # BV17: the definition-of-done table is a second list keyed by item
    # id. It went stale at amendment 6 and no review caught it.
    for i in sorted(all_ids, key=_key):
        if i not in done:
            errors.append(f"{i} has no definition of done")
        elif not done[i]:
            errors.append(f"{i} has a definition of done but no size")
    for i in sorted(set(done) - all_ids, key=_key):
        errors.append(f"{i} has a definition of done but is not an item")

    level, blocked, downstream = levels(items, set(unparsed))
    view = render(items, level, blocked, unparsed, downstream)

    if "--check" not in sys.argv:
        print(view)
        if errors:
            print("\n" + "\n".join("WARN " + e for e in errors), file=sys.stderr)
        return 0

    if errors:
        print(view)
        print("\nFAIL\n  " + "\n  ".join(errors), file=sys.stderr)
        return 1

    # Compare the derived view against the block embedded in the document.
    marker = "<!-- GENERATED by docs/plan/derive-waves.py"
    if marker not in text:
        print(view)
        print("\nFAIL the document carries no generated wave block; "
              "paste the above in", file=sys.stderr)
        return 1
    start = text.index(marker)
    end = text.index("\n\n", text.index("|---|---|", start))
    embedded = text[start:end].strip()
    if embedded != view.strip():
        print(view)
        print("\nFAIL the document's wave block is stale — regenerate",
              file=sys.stderr)
        return 1
    print(f"ok — {len(items)} items levelled, "
          f"{len(unparsed) + len(downstream)} not startable here, "
          f"{len(done)} definitions of done", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
